[package]
name = "perceptron-procgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
futures-executor = "0.3"
image = "0.24"
nalgebra = "0.31"
rand = "0.8"
wgpu = "0.14"
